[package]
name = "matrix"
version = "0.1.0"
authors = ["Jamie Blondin <jblondin@gmail.com>"]

[dependencies]
blas = { version = "0.15" }
lapack = { version = "0.11" }
num = "*"
error-chain = "*"
rand = "*"
unittest = { git = "https://github.com/jblondin/unittest" }
